version: '3.8'

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db

  node_api:
    build: ./api
    container_name: iso_api
    ports:
      - "4000:4000"
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - MONGODB_DB=${MONGODB_DB}
      - NGINX_URL=${NGINX_URL}
      - PORT=${PORT}
    volumes:
      - ./api/uploads:/app/uploads
    depends_on:
      - mongodb

  nginx_server:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./public:/usr/share/nginx/html:ro
      - ./api/uploads:/usr/share/nginx/html/uploads
  
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    container_name: jenkins_server
    user: root
    privileged: true
    # Esta es la solución integrada: se da permisos a sí mismo al arrancar
    entrypoint: >
      sh -c "chmod 666 /var/run/docker.sock && 
             chmod +x /usr/bin/docker && 
             /usr/bin/tini -- /usr/local/bin/jenkins.sh"
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    ports:
      - "8081:8080"
    networks:
      - pfinal-network
networks:
  pfinal-network:
    driver: bridge
volumes:
  jenkins_data: