version: '3.8'

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db

  node_api:
    build: ./api
    container_name: iso_api
    ports:
      - "4000:4000"
    environment:
      - MONGODB_URI=${MONGODB_URI:-mongodb://mongodb:27017}
      - MONGODB_DB=${MONGODB_DB:-IsoDB}
      - NGINX_URL=${NGINX_URL:-http://localhost:8080}
      - PORT=${PORT:-4000}
    volumes:
      - ./api/uploads:/app/uploads
    depends_on:
      - mongodb

  nginx_server:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./public:/usr/share/nginx/html:ro
      - ./api/uploads:/usr/share/nginx/html/uploads
  
  jenkins:
    build: .
    container_name: jenkins
    user: root
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

volumes:
  jenkins_home: